### PR TITLE
Make a charset conversion depending on the language

### PR DESCRIPTION
**Pull request by IvanAlegre**
due to subdb inability to set right set-encoding header

### CODE REVIEW

**Comment by arshad** [comment]
Thanks. Looks great.

**Comment by IvanAlegre** [comment]
Thanks! Just to know, are you going to release a new version?

**Comment by arshad** [comment]
Yes. I'll tag a new release.

**Comment by arshad** [comment]
@IvanAlegre I just published 1.0.3 to npm.

**Comment by IvanAlegre** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 
Thank you @arshad !

**Pull request merged**
